import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

import 'package:cinetrack/data/social_data_source.dart';
import 'package:cinetrack/data/social_payloads.dart';
import 'package:cinetrack/social/social_models.dart';

/// Golden test: what the Dart app writes and queries (SocialPayloads) must
/// equal firestore_rules_test/fixtures/social_payloads.json, which the rules
/// suite (dart_payloads.test.mjs) replays against firestore.rules. A changed
/// field/type/path fails here until the fixture is regenerated on purpose:
///   UPDATE_GOLDEN=1 flutter test test/social_payloads_golden_test.dart
/// then `npm test` in firestore_rules_test (see docs/55).
const _fixturePath = 'firestore_rules_test/fixtures/social_payloads.json';
const _photo = 'https://lh3.googleusercontent.com/a/ana';
const _uid = 'uid-ana';

Map<String, Object?> _scenarios() {
  const draft = SocialDraft(handle: 'ana_9', nickname: 'Ana', discoverable: true);
  const draftPhoto = SocialDraft(
    handle: 'ana_9',
    nickname: 'Ana',
    photoUrl: _photo,
    discoverable: false,
  );
  Map<String, Object?> change(String? photo) => {
    'uid': _uid,
    'oldHandle': 'ana',
    'newHandle': 'ana_novo',
    'nickname': 'Ana',
    'photoUrl': photo,
    'discoverable': true,
  };
  SocialWrite changeWrite(Map<String, Object?> i) => SocialPayloads.changeHandle(
    i['uid']! as String,
    oldHandle: i['oldHandle']! as String,
    newHandle: i['newHandle']! as String,
    nickname: i['nickname'],
    photoUrl: i['photoUrl'],
    discoverable: i['discoverable']! as bool,
  );
  Map<String, Object?> entry(Map<String, Object?> input, SocialWrite w) => {
    'input': input,
    'write': w.toJson(),
  };
  Map<String, Object?> draftJson(SocialDraft d) => {
    'uid': _uid,
    'handle': d.handle,
    'nickname': d.nickname,
    'photoUrl': d.photoUrl,
    'discoverable': d.discoverable,
  };
  return {
    'activate': entry(draftJson(draft), SocialPayloads.activate(_uid, draft)),
    'activate_with_photo': entry(draftJson(draftPhoto), SocialPayloads.activate(_uid, draftPhoto)),
    'changeHandle': entry(change(null), changeWrite(change(null))),
    'changeHandle_with_photo': entry(change(_photo), changeWrite(change(_photo))),
    'updateCard_nickname': entry({
      'handle': 'ana',
      'nickname': 'Nova',
    }, SocialPayloads.updateCard('ana', const CardPatch(nickname: 'Nova'))),
    'updateCard_photo_on': entry({
      'handle': 'ana',
      'photoUrl': _photo,
    }, SocialPayloads.updateCard('ana', const CardPatch(changePhoto: true, photoUrl: _photo))),
    'updateCard_photo_off': entry({
      'handle': 'ana',
      'photoUrl': null,
    }, SocialPayloads.updateCard('ana', const CardPatch(changePhoto: true))),
    'updateCard_discoverable': entry({
      'handle': 'ana',
      'discoverable': false,
    }, SocialPayloads.updateCard('ana', const CardPatch(discoverable: false))),
    'close': entry({'uid': _uid, 'handle': 'ana'}, SocialPayloads.close(_uid, handle: 'ana')),
    'close_with_invite': entry({
      'uid': _uid,
      'handle': 'ana',
      'inviteCode': 'AbCdEfGhIjKlMnOpQrStUv12',
    }, SocialPayloads.close(_uid, handle: 'ana', inviteCode: 'AbCdEfGhIjKlMnOpQrStUv12')),
    'close_pointer_only': entry({'uid': _uid}, SocialPayloads.close(_uid)),
    'sweepDelete': entry(
      {
        'uid': _uid,
        'refs': [
          'requestsSent:uid-ana_uid-x',
          'requestsReceived:uid-y_uid-ana',
          'friendships:uid-ana_uid-b',
          'blocks:uid-z',
        ],
      },
      SocialPayloads.sweepDelete(_uid, const [
        SweepRef(SweepKind.requestsSent, 'uid-ana_uid-x'),
        SweepRef(SweepKind.requestsReceived, 'uid-y_uid-ana'),
        SweepRef(SweepKind.friendships, 'uid-ana_uid-b'),
        SweepRef(SweepKind.blocks, 'uid-z'),
      ]),
    ),
  };
}

Map<String, Object?> _queries() => {
  for (final kind in SweepKind.values)
    kind.name: {'uid': _uid, 'query': SocialPayloads.sweepQuery(kind, _uid, 400).toJson()},
};

Map<String, Object?> _golden() => {
  'comment':
      'Generated by test/social_payloads_golden_test.dart (UPDATE_GOLDEN=1). Do not edit by hand.',
  'serverTimestamp': kServerTimestampJson,
  'scenarios': _scenarios(),
  'queries': _queries(),
};

void main() {
  test('Dart payloads equal the fixture the rules suite replays', () {
    final golden = jsonDecode(jsonEncode(_golden()));
    final file = File(_fixturePath);
    if (Platform.environment['UPDATE_GOLDEN'] == '1') {
      file.writeAsStringSync('${const JsonEncoder.withIndent('  ').convert(golden)}\n');
    }
    expect(file.existsSync(), isTrue, reason: 'run with UPDATE_GOLDEN=1 to create $_fixturePath');
    expect(
      golden,
      equals(jsonDecode(file.readAsStringSync())),
      reason: 'payloads changed: regenerate the fixture AND run npm test (docs/55)',
    );
  });

  test('server timestamps are marked, never real values', () {
    final text = jsonEncode(_scenarios());
    expect(text, contains(kServerTimestampJson));
    expect(const ServerTimestamp().toString(), kServerTimestampJson);
  });
}
