// Replays the payloads the Dart app writes/queries (lib/data/social_payloads.dart) against the
// FINAL rules. Nothing is copied by hand: everything comes from fixtures/social_payloads.json,
// generated by test/social_payloads_golden_test.dart (UPDATE_GOLDEN=1). If the Dart code changes
// a field, the Dart golden fails until the fixture is regenerated; if the fixture then disagrees
// with firestore.rules, THIS file fails. Flow to update: docs/55.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { after, before, beforeEach, describe, it } from 'node:test';
import { assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import {
  collection, doc, getCountFromServer, getDoc, getDocs, limit, orderBy, query, runTransaction,
  serverTimestamp, setDoc, startAfter, where, writeBatch,
} from 'firebase/firestore';
import { PHOTO, U, agoDays, commit, makeTools, newEnv, pairId } from './social_helpers.mjs';

// FIXTURE_PATH lets the mutation harness (mutations.mjs) replay a deliberately broken copy.
const fx = JSON.parse(
  readFileSync(process.env.FIXTURE_PATH ?? new URL('./fixtures/social_payloads.json', import.meta.url), 'utf8'),
);
const S = fx.scenarios;
const { ana, bruno } = U;

let env;
let t;
before(async () => {
  env = await newEnv();
  t = makeTools(env);
});
after(async () => env?.cleanup());
beforeEach(async () => env.clearFirestore());

const resolve = (v) => (v === fx.serverTimestamp ? serverTimestamp() : v);
const resolved = (data) => Object.fromEntries(Object.entries(data).map(([k, v]) => [k, resolve(v)]));
const ref = (db, path) => doc(db, ...path.split('/'));

// Executes one fixture "write" exactly as the Firestore data source does: a transaction (first
// the `reads` the payload declares, which the rules must allow; the other reads of the Dart
// side do not matter to the rules) or one batch.
const run = (db, write) => {
  if (write.mode === 'transaction') {
    return runTransaction(db, async (tx) => {
      for (const path of write.reads ?? []) await tx.get(ref(db, path));
      for (const op of write.ops) {
        const r = ref(db, op.path);
        if (op.op === 'set') tx.set(r, resolved(op.data));
        else if (op.op === 'update') tx.update(r, resolved(op.data));
        else tx.delete(r);
      }
    });
  }
  const batch = writeBatch(db);
  for (const op of write.ops) {
    const r = ref(db, op.path);
    if (op.op === 'set') batch.set(r, resolved(op.data));
    else if (op.op === 'update') batch.update(r, resolved(op.data));
    else batch.delete(r);
  }
  return batch.commit();
};

const toQuery = (db, spec) => {
  let q = collection(db, ...spec.collection.split('/'));
  const clauses = spec.where.map(([f, op, v]) => where(f, op, v));
  const order = spec.orderBy ? [orderBy(spec.orderBy[0], spec.orderBy[1])] : [];
  return query(q, ...clauses, ...order, limit(spec.limit));
};

const clone = (o) => JSON.parse(JSON.stringify(o));

describe('Dart payloads (fixture) against the final rules', () => {
  for (const name of ['activate', 'activate_with_photo']) {
    it(`${name}: card + pointer in one transaction`, async () => {
      await assertSucceeds(run(t.db(ana), S[name].write));
    });
  }

  it('activate: taken handle is denied and creates nothing', async () => {
    await t.seedSocial(bruno, { handle: S.activate.input.handle, discoverable: false });
    await assertFails(run(t.db(ana), S.activate.write));
    await t.seed(async (d) => assert.equal((await getDoc(doc(d, 'social', ana))).exists(), false));
  });

  it('activate: non-Google provider denied', async () => {
    await assertFails(run(t.dbWith(ana, 'password'), S.activate.write));
  });

  it('activate: reserved handle, 21 emoji and 41 chars denied; 20 emoji ok (derived from fixture)', async () => {
    const withHandle = (w, h) => {
      const c = clone(w);
      c.ops[0].path = `handles/${h}`;
      c.ops[1].data.handle = h;
      return c;
    };
    const withNick = (n) => {
      const c = clone(S.activate.write);
      c.ops[0].data.nickname = n;
      return c;
    };
    await assertFails(run(t.db(ana), withHandle(S.activate.write, 'admin')));
    await assertFails(run(t.db(ana), withNick('\u{1F3AC}'.repeat(21))));
    await assertFails(run(t.db(ana), withNick('x'.repeat(41))));
    await assertSucceeds(run(t.db(ana), withNick('\u{1F3AC}'.repeat(20))));
  });

  for (const [name, photo] of [['changeHandle', undefined], ['changeHandle_with_photo', PHOTO]]) {
    it(`${name}: denied before 30 days, ok after; old handle freed`, async () => {
      const i = S[name].input;
      await t.seedSocial(ana, { handle: i.oldHandle, nickname: i.nickname, changedAt: agoDays(5), photo });
      await assertFails(run(t.db(ana), S[name].write));
      await t.seedSocial(ana, { handle: i.oldHandle, nickname: i.nickname, changedAt: agoDays(31), photo });
      await assertSucceeds(run(t.db(ana), S[name].write));
      assert.equal((await getDoc(doc(t.db(ana), 'handles', i.newHandle))).exists(), true);
      assert.equal((await getDoc(doc(t.db(ana), 'handles', i.oldHandle))).exists(), false);
    });
  }

  for (const name of Object.keys(S).filter((n) => n.startsWith('updateCard_'))) {
    it(`${name}: accepted`, async () => {
      await t.seedSocial(ana, { handle: S[name].input.handle, nickname: 'Ana' });
      await assertSucceeds(run(t.db(ana), S[name].write));
    });
  }

  it('updateCard: a photo outside googleusercontent (derived from the fixture) is denied', async () => {
    await t.seedSocial(ana, { handle: 'ana', nickname: 'Ana' });
    const bad = clone(S.updateCard_photo_on.write);
    bad.ops[0].data.photoURL = 'https://evil.example/x.png';
    await assertFails(run(t.db(ana), bad));
  });

  it('harness detects divergence: a renamed field in the fixture is denied by the rules', async () => {
    const bad = clone(S.activate.write);
    bad.ops[0].data.nick = bad.ops[0].data.nickname;
    delete bad.ops[0].data.nickname;
    await assertFails(run(t.db(ana), bad));
  });

  for (const name of ['close', 'close_with_invite']) {
    it(`${name}: one batch frees handle (and invite) and removes the pointer; others untouched`, async () => {
      const i = S[name].input;
      await t.seedSocial(ana, { handle: i.handle, inviteCode: i.inviteCode });
      await t.seedSocial(bruno, { handle: 'bruno' });
      await assertSucceeds(run(t.db(ana), S[name].write));
      await t.seed(async (d) => {
        assert.equal((await getDoc(doc(d, 'social', ana))).exists(), false);
        assert.equal((await getDoc(doc(d, 'handles', i.handle))).exists(), false);
        if (i.inviteCode) assert.equal((await getDoc(doc(d, 'invites', i.inviteCode))).exists(), false);
        assert.equal((await getDoc(doc(d, 'social', bruno))).exists(), true);
      });
    });
  }

  it('close: the pointer alone (handle kept) is denied', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await assertFails(run(t.db(ana), S.close_pointer_only.write));
  });

  const seedSweepDocs = () =>
    t.seed(async (d) => {
      await setDoc(doc(d, 'friendships', 'uid-ana_uid-b'), {
        members: [ana, 'uid-b'], createdAt: agoDays(3), aName: 'A', bName: 'B',
      });
      await setDoc(doc(d, 'friend_requests', 'uid-ana_uid-x'), {
        from: ana, to: 'uid-x', fromName: 'A', toName: 'X', createdAt: agoDays(1),
      });
      await setDoc(doc(d, 'friend_requests', 'uid-y_uid-ana'), {
        from: 'uid-y', to: ana, fromName: 'Y', toName: 'A', createdAt: agoDays(1),
      });
      await setDoc(doc(d, 'users', ana, 'blocks', 'uid-z'), { createdAt: agoDays(1) });
    });

  it('sweep queries return exactly this user\'s documents and sweepDelete removes them', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await seedSweepDocs();
    const db = t.db(ana);
    const found = {};
    for (const [kind, q] of Object.entries(fx.queries)) {
      const snap = await assertSucceeds(getDocs(toQuery(db, q.query)));
      found[kind] = snap.docs.map((x) => x.id);
    }
    assert.deepEqual(found.requestsSent, ['uid-ana_uid-x']);
    assert.deepEqual(found.requestsReceived, ['uid-y_uid-ana']);
    assert.deepEqual(found.friendships, ['uid-ana_uid-b']);
    assert.deepEqual(found.blocks, ['uid-z']);
    await assertSucceeds(run(db, S.sweepDelete.write));
    for (const q of Object.values(fx.queries)) {
      assert.equal((await getDocs(toQuery(db, q.query))).empty, true);
    }
  });

  it('door closed first (account deletion order): sweepDelete still works afterwards', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await seedSweepDocs();
    const db = t.db(ana);
    await assertSucceeds(run(db, S.close.write));
    await assertSucceeds(run(db, S.sweepDelete.write));
  });

  it('account without social: sweep queries are allowed and empty', async () => {
    const db = t.db(ana);
    assert.equal((await getDoc(doc(db, 'social', ana))).exists(), false);
    for (const q of Object.values(fx.queries)) {
      assert.equal((await assertSucceeds(getDocs(toQuery(db, q.query)))).empty, true);
    }
  });
});

// ---------------------------------------------------------------------------------------------
// Slice 2 (docs/59): search, send / cancel request, "Enviados" list. Same fixture, same rules.
// ---------------------------------------------------------------------------------------------
describe('Dart payloads (fixture): friend requests (slice 2)', () => {
  const to = S.sendRequest.input.toUid; // uid-bruno
  const reqPath = `friend_requests/${ana}_${to}`;
  const bothActive = async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial(to, { handle: 'bruno' });
  };
  const clauses = (w, fn) => {
    const c = clone(w);
    fn(c.ops[0]);
    return c;
  };

  for (const name of ['sendRequest', 'sendRequest_with_photos']) {
    it(`${name}: reads are allowed and the request is created`, async () => {
      await bothActive();
      await assertSucceeds(run(t.db(ana), S[name].write));
      assert.equal(await t.exists(['friend_requests', `${ana}_${to}`]), true);
    });
  }

  it('sendRequest declares the two reads the app does (own and inverse request)', () => {
    assert.deepEqual(S.sendRequest.write.reads, [reqPath, `friend_requests/${to}_${ana}`]);
  });

  it('duplicate: a second request to the same person is denied (create over existing)', async () => {
    await bothActive();
    await assertSucceeds(run(t.db(ana), S.sendRequest.write));
    await assertFails(run(t.db(ana), S.sendRequest.write));
  });

  it('to yourself is denied', async () => {
    await bothActive();
    const self = clauses(S.sendRequest.write, (op) => {
      op.path = `friend_requests/${ana}_${ana}`;
      op.data.to = ana;
    });
    await assertFails(run(t.db(ana), self));
  });

  it('to a hidden user: the rules ALLOW it (D12: only with a known uid) but search cannot reach it', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial(to, { handle: 'bruno', discoverable: false });
    // the app finds people only through this get, which is denied for hidden cards:
    await assertFails(getDoc(doc(t.db(ana), 'handles', 'bruno')));
    await assertSucceeds(run(t.db(ana), S.sendRequest.write));
  });

  it('to someone who blocked you, or whom you blocked: denied (and the card is not readable)', async () => {
    await bothActive();
    await t.seedBlock(to, ana);
    await assertFails(getDoc(doc(t.db(ana), 'handles', 'bruno')));
    await assertFails(run(t.db(ana), S.sendRequest.write));
    await env.clearFirestore();
    await bothActive();
    await t.seedBlock(ana, to);
    await assertFails(getDoc(doc(t.db(ana), 'handles', 'bruno')));
    await assertFails(run(t.db(ana), S.sendRequest.write));
  });

  it('to someone without social is denied', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await assertFails(run(t.db(ana), S.sendRequest.write));
  });

  it('sender without social is denied', async () => {
    await t.seedSocial(to, { handle: 'bruno' });
    await assertFails(run(t.db(ana), S.sendRequest.write));
  });

  it('non-Google provider is denied', async () => {
    await bothActive();
    await assertFails(run(t.dbWith(ana, 'password'), S.sendRequest.write));
  });

  it('unknown handle: the get is allowed and says "does not exist" (the app shows the generic message)', async () => {
    const snap = await assertSucceeds(getDoc(doc(t.db(ana), 'handles', 'ninguem')));
    assert.equal(snap.exists(), false);
  });

  it('a request to a uid with "_" is denied (ambiguous composite id)', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial('uid_x', { handle: 'xis' });
    const bad = clauses(S.sendRequest.write, (op) => {
      op.path = `friend_requests/${ana}_uid_x`;
      op.data.to = 'uid_x';
    });
    await assertFails(run(t.db(ana), bad));
  });

  it('field limits (derived from the fixture): extra field, forged sender, id mismatch, names, photos, clock', async () => {
    await bothActive();
    const w = S.sendRequest_with_photos.write;
    const bad = {
      'extra field': (op) => (op.data.note = 'oi'),
      'sender forged': (op) => (op.data.from = to),
      'id mismatch': (op) => (op.path = `friend_requests/${ana}_uid-caio`),
      'fromName empty': (op) => (op.data.fromName = '   '),
      'toName 41 chars': (op) => (op.data.toName = 'x'.repeat(41)),
      'toName with zero-width space': (op) => (op.data.toName = 'Bru\u200Bno'),
      'fromPhoto outside Google': (op) => (op.data.fromPhoto = 'https://evil.example/x.png'),
      'toPhoto http': (op) => (op.data.toPhoto = 'http://lh3.googleusercontent.com/a'),
      'client clock': (op) => (op.data.createdAt = new Date().toISOString()),
      'missing toName': (op) => delete op.data.toName,
    };
    for (const [label, edit] of Object.entries(bad)) {
      await assertFails(run(t.db(ana), clauses(w, edit)), label);
    }
    // 20 emoji (40 UTF-16 units) is the largest valid name
    await assertSucceeds(
      run(t.db(ana), clauses(w, (op) => (op.data.toName = '\u{1F3AC}'.repeat(20)))),
    );
  });

  it('cancel: the sender deletes their own request; repeating it is harmless', async () => {
    await bothActive();
    await t.seedRequest(ana, to);
    await assertSucceeds(run(t.db(ana), S.cancelRequest.write));
    assert.equal(await t.exists(['friend_requests', `${ana}_${to}`]), false);
    await assertSucceeds(run(t.db(ana), S.cancelRequest.write));
  });

  it('cancel: a request of someone else is denied (and survives); so is an id without my uid', async () => {
    await bothActive();
    await t.seedRequest(to, 'uid-caio');
    const other = clone(S.cancelRequest.write);
    other.ops[0].path = `friend_requests/${to}_uid-caio`;
    await assertFails(run(t.db(ana), other));
    assert.equal(await t.exists(['friend_requests', `${to}_uid-caio`]), true);
    // a non-existing document whose id does not contain my uid: denied too
    const ghost = clone(S.cancelRequest.write);
    ghost.ops[0].path = 'friend_requests/uid-x_uid-y';
    await assertFails(run(t.db(ana), ghost));
  });

  it('sent query: only my pending requests, newest first, paged with startAfter; others cannot run it', async () => {
    await bothActive();
    await t.seed(async (d) => {
      const mk = (id, from, toUid, days) =>
        setDoc(doc(d, 'friend_requests', id), {
          from, to: toUid, fromName: 'F', toName: 'T', createdAt: agoDays(days),
        });
      await mk(`${ana}_uid-x1`, ana, 'uid-x1', 3);
      await mk(`${ana}_uid-x2`, ana, 'uid-x2', 1);
      await mk(`${ana}_uid-x3`, ana, 'uid-x3', 2);
      await mk(`${to}_${ana}`, to, ana, 0.5); // received: must not appear
      await mk(`${to}_uid-caio`, to, 'uid-caio', 0.5); // someone else's: must not appear
    });
    const spec = fx.requestQueries.sent.query;
    const db = t.db(ana);
    const first = await assertSucceeds(getDocs(toQuery(db, { ...spec, limit: 3 })));
    assert.deepEqual(first.docs.map((x) => x.id), [`${ana}_uid-x2`, `${ana}_uid-x3`, `${ana}_uid-x1`]);
    // page size 2 (+1 look-ahead), then continue after the 2nd document
    const p1 = await getDocs(toQuery(db, { ...spec, limit: 3 }));
    const page2 = await assertSucceeds(
      getDocs(query(toQuery(db, { ...spec, limit: 3 }), startAfter(p1.docs[1]))),
    );
    assert.deepEqual(page2.docs.map((x) => x.id), [`${ana}_uid-x1`]);
    // the same query run by another user (from == ana) is denied
    await assertFails(getDocs(toQuery(t.db(to), spec)));
    await assertFails(getDocs(toQuery(t.anon(), spec)));
  });

  it('sentCount query: counts only my sent requests (limit as in the payload); others are denied', async () => {
    await bothActive();
    await t.seedRequest(ana, 'uid-x1');
    await t.seedRequest(ana, 'uid-x2');
    await t.seedRequest(to, ana);
    const spec = fx.requestQueries.sentCount.query;
    assert.equal(spec.aggregate, 'count');
    const snap = await assertSucceeds(getCountFromServer(toQuery(t.db(ana), spec)));
    assert.equal(snap.data().count, 2);
    await assertFails(getCountFromServer(toQuery(t.db(to), spec)));
  });

  it('crossed request: the inverse request is readable (the app detects it) and nothing becomes a friendship', async () => {
    await bothActive();
    await t.seedRequest(to, ana);
    await assertSucceeds(getDoc(doc(t.db(ana), 'friend_requests', `${to}_${ana}`)));
    // the app stops here ("essa pessoa já enviou um pedido para você"); the pair is slice 3
    assert.equal(await t.exists(['friendships', 'uid-ana_uid-bruno']), false);
  });

  it('lookup: the exact document the app reads (fixture path): visible card ok, hidden / blocked denied, missing = no document', async () => {
    const path = fx.lookups.handle.get;
    assert.equal(path, 'handles/bruno');
    await bothActive();
    const visible = await assertSucceeds(getDoc(ref(t.db(ana), path)));
    assert.equal(visible.data().nickname, 'Nome uid-bruno');
    const none = await assertSucceeds(getDoc(ref(t.db(ana), 'handles/ninguem')));
    assert.equal(none.exists(), false);
    await env.clearFirestore();
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial(to, { handle: 'bruno', discoverable: false });
    await assertFails(getDoc(ref(t.db(ana), path)));
    await assertFails(getDoc(ref(t.anon(), path)));
  });
});

// ---------------------------------------------------------------------------------------------
// Slice 3 (docs/62): receive / accept / decline / list / remove friends, and the crossed request
// (D4). Same fixture, same rules: nothing about the payloads is copied by hand.
// ---------------------------------------------------------------------------------------------
describe('Dart payloads (fixture): accept, decline, friends, remove (slice 3)', () => {
  const bru = bruno;
  const caio = U.caio;
  const pair = `friendships/${ana}_${bru}`; // ana < bruno
  const acc = S.acceptRequest;
  const bothActive = async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial(bru, { handle: 'bruno' });
  };
  // The pending request the accept payload refers to (their half = what THEIR request says).
  const seedTheirs = (i = acc.input, extra = {}) =>
    t.seedRequest(i.fromUid, i.uid, { fromName: i.fromName, fromPhoto: i.fromPhoto, ...extra });
  const edit = (w, fn) => {
    const c = clone(w);
    fn(c.ops[0], c);
    return c;
  };

  it('accept declares ONE batch: the pair + both requests deleted (derived from the fixture)', () => {
    for (const name of ['acceptRequest', 'acceptRequest_with_photos', 'acceptRequest_as_b']) {
      const w = S[name].write;
      assert.equal(w.mode, 'batch');
      assert.deepEqual(w.ops.map((o) => o.op), ['set', 'delete', 'delete']);
      const { uid, fromUid } = S[name].input;
      assert.deepEqual(w.ops.slice(1).map((o) => o.path).sort(), [
        `friend_requests/${fromUid}_${uid}`,
        `friend_requests/${uid}_${fromUid}`,
      ].sort());
    }
  });

  for (const name of ['acceptRequest', 'acceptRequest_with_photos', 'acceptRequest_as_b']) {
    it(`${name}: creates the pair and consumes the request in the same batch`, async () => {
      const i = S[name].input;
      await bothActive();
      await seedTheirs(i);
      await assertSucceeds(run(t.db(i.uid), S[name].write));
      await t.seed(async (d) => {
        const w = S[name].write.ops[0];
        const snap = await getDoc(ref(d, w.path));
        assert.equal(snap.exists(), true);
        const [lo, hi] = snap.data().members;
        assert.ok(lo < hi);
        assert.equal(snap.data()[lo === i.uid ? 'aName' : 'bName'], i.myName);
        assert.equal(snap.data()[lo === i.uid ? 'bName' : 'aName'], i.fromName);
      });
      assert.equal(await t.exists(['friend_requests', `${i.fromUid}_${i.uid}`]), false);
      assert.equal(await t.exists(['friend_requests', `${i.uid}_${i.fromUid}`]), false);
    });
  }

  it('accept without their pending request is denied (nothing created)', async () => {
    await bothActive();
    await assertFails(run(t.db(ana), acc.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), false);
  });

  it('accepting my OWN request (the sender confirms) is denied', async () => {
    await bothActive();
    await t.seedRequest(ana, bru, { fromName: 'Bruno' });
    await assertFails(run(t.db(ana), acc.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), false);
  });

  it('accepting a request addressed to somebody else is denied; so is a third party creating the pair', async () => {
    await bothActive();
    await t.seedSocial(caio, { handle: 'caio' });
    await seedTheirs(acc.input, {});
    await t.seedRequest(bru, caio, { fromName: 'Bruno' });
    // caio tries to use the request bruno -> ana
    const forged = edit(acc.write, (op) => {
      op.data.members = [ana, caio];
      op.path = `friendships/${ana}_${caio}`;
    });
    await assertFails(run(t.db(caio), forged));
    await assertFails(run(t.db(caio), acc.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), false);
  });

  it('accepting twice: the second batch is denied and nothing changes', async () => {
    await bothActive();
    await seedTheirs();
    await assertSucceeds(run(t.db(ana), acc.write));
    await assertFails(run(t.db(ana), acc.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), true);
  });

  it('accept that leaves the request behind (create only, no delete) is denied', async () => {
    await bothActive();
    await seedTheirs();
    const keep = clone(acc.write);
    keep.ops = [keep.ops[0]];
    await assertFails(run(t.db(ana), keep));
    const half = clone(acc.write);
    half.ops = [half.ops[0], half.ops[1]];
    // deleting only {other}_{me} is fine when {me}_{other} does not exist...
    await assertSucceeds(run(t.db(ana), half));
  });

  it('with BOTH requests pending, deleting only THEIR request is denied (mine must go too)', async () => {
    await bothActive();
    await t.seedRequest(bru, ana, { fromName: acc.input.fromName });
    await t.seedRequest(ana, bru);
    const half = clone(acc.write);
    half.ops = half.ops.filter((o) => o.path !== `friend_requests/${ana}_${bru}`);
    await assertFails(run(t.db(ana), half));
    await assertSucceeds(run(t.db(ana), acc.write));
  });

  it('the other person\'s half cannot be forged (name or photo different from THEIR request)', async () => {
    await bothActive();
    await seedTheirs();
    const bnameKey = 'bName'; // ana < bruno: the other half is "b"
    await assertFails(run(t.db(ana), edit(acc.write, (op) => (op.data[bnameKey] = 'Outro Nome'))));
    await assertFails(
      run(t.db(ana), edit(acc.write, (op) => (op.data.bPhoto = 'https://lh3.googleusercontent.com/x'))),
    );
  });

  it('field limits (derived from the fixture): extra field, names, photo host, clock, order, id, members', async () => {
    await bothActive();
    await seedTheirs(S.acceptRequest_with_photos.input);
    const w = S.acceptRequest_with_photos.write;
    const bad = {
      'extra field': (op) => (op.data.note = 'oi'),
      'my name empty': (op) => (op.data.aName = '  '),
      'my name 41 chars': (op) => (op.data.aName = 'x'.repeat(41)),
      'my name with zero-width space': (op) => (op.data.aName = 'An​a'),
      'my photo outside Google': (op) => (op.data.aPhoto = 'https://evil.example/x.png'),
      'client clock': (op) => (op.data.createdAt = new Date().toISOString()),
      'members out of order': (op) => (op.data.members = [bru, ana]),
      'three members': (op) => (op.data.members = [ana, bru, U.caio]),
      'id mismatch': (op) => (op.path = `friendships/${bru}_${ana}`),
      'missing aName': (op) => delete op.data.aName,
    };
    for (const [label, fn] of Object.entries(bad)) {
      await assertFails(run(t.db(ana), edit(w, fn)), label);
    }
    // 20 emoji (40 UTF-16 units) is the largest valid name
    await assertSucceeds(run(t.db(ana), edit(w, (op) => (op.data.aName = '\u{1F3AC}'.repeat(20)))));
  });

  it('accept is denied when either side blocked the other, without social, or when not Google', async () => {
    const i = acc.input;
    await bothActive();
    await seedTheirs(i);
    await t.seedBlock(bru, ana);
    await assertFails(run(t.db(ana), acc.write));
    await env.clearFirestore();
    await bothActive();
    await seedTheirs(i);
    await t.seedBlock(ana, bru);
    await assertFails(run(t.db(ana), acc.write));
    await env.clearFirestore();
    // the other person turned friendships off (their social is gone)
    await t.seedSocial(ana, { handle: 'ana' });
    await seedTheirs(i);
    await assertFails(run(t.db(ana), acc.write));
    await env.clearFirestore();
    // I never turned them on
    await t.seedSocial(bru, { handle: 'bruno' });
    await seedTheirs(i);
    await assertFails(run(t.db(ana), acc.write));
    await env.clearFirestore();
    await bothActive();
    await seedTheirs(i);
    await assertFails(run(t.dbWith(ana, 'password'), acc.write));
    await assertSucceeds(run(t.db(ana), acc.write));
  });

  it('crossed request (D4): the app reads the inverse, then ONE batch makes the friendship and leaves nothing pending', async () => {
    await bothActive();
    await t.seedRequest(bru, ana, { fromName: acc.input.fromName });
    const send = S.sendRequest.write;
    // the transaction reads the inverse (allowed) ...
    const db = t.db(ana);
    await assertSucceeds(
      runTransaction(db, async (tx) => {
        for (const path of send.reads) await tx.get(ref(db, path));
      }),
    );
    // ... and the accept batch (the same payload as "Aceitar") closes it
    await assertSucceeds(run(db, acc.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), true);
    assert.equal(await t.exists(['friend_requests', `${bru}_${ana}`]), false);
    assert.equal(await t.exists(['friend_requests', `${ana}_${bru}`]), false);
  });

  it('crossed request when BOTH requests exist (race): both are consumed', async () => {
    await bothActive();
    await t.seedRequest(bru, ana, { fromName: acc.input.fromName });
    await t.seedRequest(ana, bru);
    await assertSucceeds(run(t.db(ana), acc.write));
    assert.equal(await t.exists(['friend_requests', `${bru}_${ana}`]), false);
    assert.equal(await t.exists(['friend_requests', `${ana}_${bru}`]), false);
  });

  it('crossed request: creating the pending request instead (old provisional path) is still allowed by the rules; the app no longer does it', async () => {
    // Documented so nobody mistakes the rules for the guard: the app decides, the rules only protect.
    await bothActive();
    await t.seedRequest(bru, ana);
    await assertSucceeds(run(t.db(ana), S.sendRequest.write));
  });

  it('decline: the recipient deletes the request silently; repeating it is harmless; the sender can still cancel', async () => {
    const d = S.declineRequest;
    await bothActive();
    await t.seedRequest(d.input.fromUid, ana);
    await assertSucceeds(run(t.db(ana), d.write));
    assert.equal(await t.exists(['friend_requests', `${bru}_${ana}`]), false);
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), false);
    await assertSucceeds(run(t.db(ana), d.write));
  });

  it('decline: a request between two other people is denied (and survives); so is an id without my uid', async () => {
    await bothActive();
    await t.seedRequest(bru, U.caio);
    const other = edit(S.declineRequest.write, (op) => (op.path = `friend_requests/${bru}_${U.caio}`));
    await assertFails(run(t.db(ana), other));
    assert.equal(await t.exists(['friend_requests', `${bru}_${U.caio}`]), true);
    const ghost = edit(S.declineRequest.write, (op) => (op.path = 'friend_requests/uid-x_uid-y'));
    await assertFails(run(t.db(ana), ghost));
  });

  it('remove friend: either side removes the one pair document for both; repeating is harmless', async () => {
    await t.seedFriendship(ana, bru);
    await assertSucceeds(run(t.db(ana), S.removeFriend.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), false);
    await assertSucceeds(run(t.db(ana), S.removeFriend.write));
    await t.seedFriendship(ana, bru);
    // the other side runs the same pair delete
    const asBruno = edit(S.removeFriend.write, () => {});
    await assertSucceeds(run(t.db(bru), asBruno));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), false);
  });

  it('remove friend: a third party is denied (the pair survives); a pair without my uid is denied even if missing', async () => {
    await t.seedFriendship(ana, bru);
    await assertFails(run(t.db(U.caio), S.removeFriend.write));
    assert.equal(await t.exists(['friendships', `${ana}_${bru}`]), true);
    const ghost = edit(S.removeFriend.write, (op) => (op.path = 'friendships/uid-x_uid-y'));
    await assertFails(run(t.db(ana), ghost));
  });

  it('after removing a friend a new request is possible again (and while friends it is denied)', async () => {
    await bothActive();
    await t.seedFriendship(ana, bru);
    await assertFails(run(t.db(ana), S.sendRequest.write));
    await assertSucceeds(run(t.db(ana), S.removeFriend.write));
    await assertSucceeds(run(t.db(ana), S.sendRequest.write));
  });

  it('received query: only requests addressed to me, newest first, paged with startAfter; others are denied', async () => {
    await bothActive();
    await t.seed(async (d) => {
      const mk = (id, from, toUid, days) =>
        setDoc(doc(d, 'friend_requests', id), {
          from, to: toUid, fromName: 'F', toName: 'T', createdAt: agoDays(days),
        });
      await mk(`uid-x1_${ana}`, 'uid-x1', ana, 3);
      await mk(`uid-x2_${ana}`, 'uid-x2', ana, 1);
      await mk(`uid-x3_${ana}`, 'uid-x3', ana, 2);
      await mk(`${ana}_${bru}`, ana, bru, 0.5); // sent: must not appear
      await mk(`uid-x1_${bru}`, 'uid-x1', bru, 0.5); // somebody else's
    });
    const spec = fx.requestQueries.received.query;
    const db = t.db(ana);
    const first = await assertSucceeds(getDocs(toQuery(db, { ...spec, limit: 3 })));
    assert.deepEqual(first.docs.map((x) => x.id), [`uid-x2_${ana}`, `uid-x3_${ana}`, `uid-x1_${ana}`]);
    const page2 = await assertSucceeds(
      getDocs(query(toQuery(db, { ...spec, limit: 3 }), startAfter(first.docs[1]))),
    );
    assert.deepEqual(page2.docs.map((x) => x.id), [`uid-x1_${ana}`]);
    await assertFails(getDocs(toQuery(t.db(bru), spec)));
    await assertFails(getDocs(toQuery(t.anon(), spec)));
  });

  it('receivedCount query: counts only mine (capped by the payload limit); others are denied', async () => {
    await bothActive();
    await t.seedRequest('uid-x1', ana);
    await t.seedRequest('uid-x2', ana);
    await t.seedRequest(ana, bru);
    const spec = fx.requestQueries.receivedCount.query;
    assert.equal(spec.aggregate, 'count');
    const snap = await assertSucceeds(getCountFromServer(toQuery(t.db(ana), spec)));
    assert.equal(snap.data().count, 2);
    await assertFails(getCountFromServer(toQuery(t.db(bru), spec)));
    // an account without friendships may count too (0): the app asks before the state is known
    const lone = await assertSucceeds(getCountFromServer(toQuery(t.db('uid-lone'), {
      ...spec, where: [['to', '==', 'uid-lone']],
    })));
    assert.equal(lone.data().count, 0);
  });

  it('friends query: only my pairs, paged with startAfter, both sides list it; others are denied', async () => {
    await t.seedFriendship(ana, bru);
    await t.seedFriendship(ana, U.caio);
    await t.seedFriendship(ana, U.dora);
    await t.seedFriendship(bru, U.dora); // not mine
    const spec = fx.requestQueries.friends.query;
    assert.deepEqual(spec.where, [['members', 'array-contains', ana]]);
    const db = t.db(ana);
    const first = await assertSucceeds(getDocs(toQuery(db, { ...spec, limit: 2 })));
    assert.equal(first.docs.length, 2);
    const rest = await assertSucceeds(
      getDocs(query(toQuery(db, { ...spec, limit: 3 }), startAfter(first.docs[1]))),
    );
    assert.equal(rest.docs.length, 1);
    const all = [...first.docs, ...rest.docs].map((x) => x.id).sort();
    assert.deepEqual(all, [`${ana}_${U.caio}`, `${ana}_${bru}`, `${ana}_${U.dora}`].sort());
    // the other side lists the same pair, with its own uid
    const theirs = await assertSucceeds(
      getDocs(toQuery(t.db(bru), { ...spec, where: [['members', 'array-contains', bru]] })),
    );
    assert.deepEqual(theirs.docs.map((x) => x.id).sort(), [`${ana}_${bru}`, `${bru}_${U.dora}`].sort());
    await assertFails(getDocs(toQuery(t.db(U.caio), spec)));
    await assertFails(getDocs(toQuery(t.anon(), spec)));
  });

  it('friendsCount query: counts only my pairs; others are denied', async () => {
    await t.seedFriendship(ana, bru);
    await t.seedFriendship(bru, U.dora);
    const spec = fx.requestQueries.friendsCount.query;
    assert.equal(spec.aggregate, 'count');
    const snap = await assertSucceeds(getCountFromServer(toQuery(t.db(ana), spec)));
    assert.equal(snap.data().count, 1);
    await assertFails(getCountFromServer(toQuery(t.db(bru), spec)));
  });

  it('deactivate sweep still removes real friendships and requests (both sides lose the pair)', async () => {
    await bothActive();
    await t.seedFriendship(ana, bru);
    await t.seedRequest('uid-x', ana);
    await t.seedRequest(ana, 'uid-y');
    const db = t.db(ana);
    const friends = await getDocs(toQuery(db, fx.queries.friendships.query));
    assert.deepEqual(friends.docs.map((x) => x.id), [`${ana}_${bru}`]);
    await assertSucceeds(run(db, S.close.write));
    await assertSucceeds(
      run(db, {
        mode: 'batch',
        ops: [
          { op: 'delete', path: `friendships/${ana}_${bru}` },
          { op: 'delete', path: `friend_requests/uid-x_${ana}` },
          { op: 'delete', path: `friend_requests/${ana}_uid-y` },
        ],
      }),
    );
    // Bruno's list no longer has Ana
    const theirs = await getDocs(toQuery(t.db(bru), { ...fx.queries.friendships.query, where: [['members', 'array-contains', bru]] }));
    assert.equal(theirs.empty, true);
  });
});

// ---------------------------------------------------------------------------------------------
// Slice 4 (docs/65): block, unblock, list the blocked, and what a block does to the other
// operations. Same fixture, same rules: nothing about the payloads is copied by hand.
// ---------------------------------------------------------------------------------------------
describe('Dart payloads (fixture): block, unblock, blocked list (slice 4)', () => {
  const bru = bruno;
  const caio = U.caio;
  const blk = S.blockUser;
  const blockPath = `users/${ana}/blocks/${bru}`;
  const pairPath = `friendships/${ana}_${bru}`;
  const sentPath = `friend_requests/${ana}_${bru}`;
  const recvPath = `friend_requests/${bru}_${ana}`;
  const bothActive = async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial(bru, { handle: 'bruno' });
  };
  const has = (path) => t.exists(path.split('/'));
  const without = (w, path) => {
    const c = clone(w);
    c.ops = c.ops.filter((o) => o.path !== path);
    return c;
  };
  const edit = (w, fn) => {
    const c = clone(w);
    fn(c.ops[0], c);
    return c;
  };
  // The state of the relationship before blocking: which of the three documents exist.
  const STATES = {
    'nothing (never interacted)': {},
    'only a friendship': { pair: true },
    'only a received request': { recv: true },
    'only a sent request': { sent: true },
    'both requests': { sent: true, recv: true },
    'friendship and both requests (race)': { pair: true, sent: true, recv: true },
  };
  const seedState = async (s) => {
    await bothActive();
    if (s.pair) await t.seedFriendship(ana, bru);
    if (s.sent) await t.seedRequest(ana, bru);
    if (s.recv) await t.seedRequest(bru, ana);
  };

  it('the block is ONE batch: create the block, delete the pair and BOTH requests (from the fixture)', () => {
    for (const name of ['blockUser', 'blockUser_with_photo', 'blockUser_bare']) {
      const w = S[name].write;
      assert.equal(w.mode, 'batch');
      assert.equal(w.reads, undefined, 'no read first');
      assert.deepEqual(w.ops.map((o) => o.op), ['set', 'delete', 'delete', 'delete']);
      assert.equal(w.ops[0].path, blockPath);
      assert.deepEqual(w.ops.slice(1).map((o) => o.path).sort(), [pairPath, sentPath, recvPath].sort());
    }
    assert.deepEqual(Object.keys(S.blockUser_bare.write.ops[0].data), ['createdAt']);
    assert.equal(S.unblockUser.write.ops.length, 1);
    assert.equal(S.unblockUser.write.ops[0].op, 'delete');
  });

  for (const name of ['blockUser', 'blockUser_with_photo', 'blockUser_bare']) {
    for (const [label, s] of Object.entries(STATES)) {
      it(`${name} with ${label}: accepted; afterwards no friendship and no request in either direction`, async () => {
        await seedState(s);
        await assertSucceeds(run(t.db(ana), S[name].write));
        const snap = await getDoc(ref(t.db(ana), blockPath));
        assert.equal(snap.exists(), true);
        assert.equal(snap.data().blockedName, S[name].input.name ?? undefined);
        assert.equal(await has(pairPath), false);
        assert.equal(await has(sentPath), false);
        assert.equal(await has(recvPath), false);
      });
    }
  }

  it('the other side of a friendship can block too (pair id sorts the other way)', async () => {
    await bothActive();
    await t.seedFriendship(ana, bru);
    // Bruno blocks Ana: the same shape as the fixture payload, with the uids swapped.
    const swapped = {
      mode: 'batch',
      ops: [
        { op: 'set', path: `users/${bru}/blocks/${ana}`, data: clone(blk.write.ops[0].data) },
        { op: 'delete', path: pairPath },
        { op: 'delete', path: `friend_requests/${bru}_${ana}` },
        { op: 'delete', path: `friend_requests/${ana}_${bru}` },
      ],
    };
    await assertSucceeds(run(t.db(bru), swapped));
    assert.equal(await has(pairPath), false);
    assert.equal(await has(`users/${bru}/blocks/${ana}`), true);
  });

  it('blocking WITHOUT the right batch is denied: each missing delete is refused when its document exists', async () => {
    await seedState({ pair: true, sent: true, recv: true });
    const w = blk.write;
    await assertFails(run(t.db(ana), without(w, pairPath)));
    await assertFails(run(t.db(ana), without(w, sentPath)));
    await assertFails(run(t.db(ana), without(w, recvPath)));
    await assertFails(run(t.db(ana), { mode: 'batch', ops: [w.ops[0]] }));
    assert.equal(await has(blockPath), false, 'nothing is created by a refused batch');
    assert.equal(await has(pairPath), true);
    await assertSucceeds(run(t.db(ana), w));
  });

  it('a lone `set` of the block is fine when nothing exists to delete (the deletes are only for what exists)', async () => {
    await bothActive();
    await assertSucceeds(run(t.db(ana), { mode: 'batch', ops: [blk.write.ops[0]] }));
  });

  it('blocking myself is denied', async () => {
    await bothActive();
    const self = edit(blk.write, (op, c) => {
      op.path = `users/${ana}/blocks/${ana}`;
      c.ops = [op];
    });
    await assertFails(run(t.db(ana), self));
  });

  it('blocking twice: the second batch is an update, denied; the first block is untouched', async () => {
    await seedState({ pair: true });
    await assertSucceeds(run(t.db(ana), blk.write));
    const before = (await getDoc(ref(t.db(ana), blockPath))).data();
    await assertFails(run(t.db(ana), S.blockUser_with_photo.write));
    const after = (await getDoc(ref(t.db(ana), blockPath))).data();
    assert.deepEqual(after, before);
  });

  it('blocking somebody who never turned friendships on is accepted (the block is only mine); so is a non-Google session', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await assertSucceeds(run(t.db(ana), blk.write));
    await env.clearFirestore();
    await bothActive();
    await assertSucceeds(run(t.dbWith(ana, 'password'), blk.write));
  });

  it('only the owner creates a block under their own uid: a third party and anonymous are denied', async () => {
    await bothActive();
    await assertFails(run(t.db(bru), blk.write));
    await assertFails(run(t.db(caio), blk.write));
    await assertFails(run(t.anon(), blk.write));
    assert.equal(await has(blockPath), false);
  });

  it('field limits (derived from the fixture): extra field, name, photo host, client clock, missing createdAt', async () => {
    await bothActive();
    const w = S.blockUser_with_photo.write;
    const bad = {
      'extra field': (op) => (op.data.note = 'oi'),
      'name empty': (op) => (op.data.blockedName = '  '),
      'name 41 chars': (op) => (op.data.blockedName = 'x'.repeat(41)),
      'name with zero-width space': (op) => (op.data.blockedName = 'Br​uno'),
      'photo outside Google': (op) => (op.data.blockedPhoto = 'https://evil.example/x.png'),
      'client clock': (op) => (op.data.createdAt = new Date().toISOString()),
      'no createdAt': (op) => delete op.data.createdAt,
    };
    for (const [label, fn] of Object.entries(bad)) {
      await assertFails(run(t.db(ana), edit(w, fn)), label);
    }
    await assertSucceeds(run(t.db(ana), edit(w, (op) => (op.data.blockedName = '\u{1F3AC}'.repeat(20)))));
  });

  it('uids with "_" or "/" cannot be blocked (ambiguous composite ids)', async () => {
    await bothActive();
    const w = edit(blk.write, (op) => (op.path = `users/${ana}/blocks/uid_x`));
    await assertFails(run(t.db(ana), w));
  });

  it('blocking N people in ONE batch is recorded (the app blocks one per batch)', async () => {
    const out = {};
    for (const n of [1, 3, 6, 7]) {
      await env.clearFirestore();
      await t.seedSocial(ana, { handle: 'ana' });
      const others = Array.from({ length: n }, (_, i) => `u${i}`);
      for (const o of others) {
        await t.seedSocial(o, { handle: `h${o}` });
        await t.seedFriendship(ana, o);
        await t.seedRequest(ana, o);
        await t.seedRequest(o, ana);
      }
      const d = t.db(ana);
      out[n] = await commit(d, (b) => {
        for (const o of others) {
          b.set(doc(d, 'users', ana, 'blocks', o), { createdAt: serverTimestamp() });
          b.delete(doc(d, 'friendships', pairId(ana, o)));
          b.delete(doc(d, 'friend_requests', `${ana}_${o}`));
          b.delete(doc(d, 'friend_requests', `${o}_${ana}`));
        }
      }).then(() => 'ok', (e) => e.code);
    }
    console.log('block N in one batch (emulator):', JSON.stringify(out));
    assert.equal(out[1], 'ok');
    assert.equal(out[3], 'ok');
  });

  // ---- unblock ----
  it('unblock: the owner deletes the block; the friendship and the requests are NOT restored', async () => {
    await seedState({ pair: true, sent: true, recv: true });
    await assertSucceeds(run(t.db(ana), blk.write));
    await assertSucceeds(run(t.db(ana), S.unblockUser.write));
    assert.equal(await has(blockPath), false);
    assert.equal(await has(pairPath), false);
    assert.equal(await has(sentPath), false);
    assert.equal(await has(recvPath), false);
  });

  it('unblock of a block that does not exist is accepted (idempotent); repeating is harmless', async () => {
    await bothActive();
    await assertSucceeds(run(t.db(ana), S.unblockUser.write));
    await assertSucceeds(run(t.db(ana), blk.write));
    await assertSucceeds(run(t.db(ana), S.unblockUser.write));
    await assertSucceeds(run(t.db(ana), S.unblockUser.write));
  });

  it('unblock: I cannot delete a block that SOMEBODY ELSE made (not even to find out whether it exists)', async () => {
    await bothActive();
    await t.seedBlock(bru, ana);
    const theirs = edit(S.unblockUser.write, (op) => (op.path = `users/${bru}/blocks/${ana}`));
    await assertFails(run(t.db(ana), theirs));
    assert.equal(await has(`users/${bru}/blocks/${ana}`), true);
    const none = edit(S.unblockUser.write, (op) => (op.path = `users/${bru}/blocks/${caio}`));
    await assertFails(run(t.db(ana), none));
    // the blocked person cannot delete the block against them either
    await assertFails(run(t.db(caio), S.unblockUser.write));
  });

  it('after unblocking, a new request is possible again (the block never restored anything)', async () => {
    await seedState({ pair: true });
    await assertSucceeds(run(t.db(ana), blk.write));
    await assertFails(run(t.db(ana), S.sendRequest.write));
    await assertSucceeds(run(t.db(ana), S.unblockUser.write));
    await assertSucceeds(run(t.db(ana), S.sendRequest.write));
    assert.equal(await has(pairPath), false);
  });

  // ---- list ----
  it('blocked query: only MY blocks, newest first, paged with startAfter; nobody else can run it', async () => {
    await bothActive();
    await t.seed(async (d) => {
      const mk = (owner, id, days) =>
        setDoc(doc(d, 'users', owner, 'blocks', id), { blockedName: id, createdAt: agoDays(days) });
      await mk(ana, 'uid-x1', 3);
      await mk(ana, 'uid-x2', 1);
      await mk(ana, 'uid-x3', 2);
      await mk(bru, 'uid-y1', 1); // somebody else's block: must not appear
    });
    const spec = fx.requestQueries.blocked.query;
    assert.equal(spec.collection, `users/${ana}/blocks`);
    assert.deepEqual(spec.where, []);
    const db = t.db(ana);
    const first = await assertSucceeds(getDocs(toQuery(db, { ...spec, limit: 3 })));
    assert.deepEqual(first.docs.map((x) => x.id), ['uid-x2', 'uid-x3', 'uid-x1']);
    const page2 = await assertSucceeds(
      getDocs(query(toQuery(db, { ...spec, limit: 3 }), startAfter(first.docs[1]))),
    );
    assert.deepEqual(page2.docs.map((x) => x.id), ['uid-x1']);
    await assertFails(getDocs(toQuery(t.db(bru), spec)));
    await assertFails(getDocs(toQuery(t.db(caio), spec)));
    await assertFails(getDocs(toQuery(t.anon(), spec)));
  });

  it('the blocked person cannot read the block (get or list), nor learn it exists', async () => {
    await seedState({ pair: true });
    await assertSucceeds(run(t.db(ana), blk.write));
    await assertFails(getDoc(ref(t.db(bru), blockPath)));
    await assertFails(getDocs(toQuery(t.db(bru), fx.requestQueries.blocked.query)));
    await assertSucceeds(getDoc(ref(t.db(ana), blockPath)));
    // Bruno's own lists show nothing of Ana: the friendship and both requests are gone
    const theirs = await getDocs(
      toQuery(t.db(bru), { ...fx.requestQueries.friends.query, where: [['members', 'array-contains', bru]] }),
    );
    assert.equal(theirs.empty, true);
  });

  // ---- effect of a block on the other operations ----
  it('whoever was blocked cannot send a request to the blocker (denied) and nothing is created', async () => {
    await bothActive();
    await assertSucceeds(run(t.db(ana), blk.write));
    const fromBruno = edit(S.sendRequest.write, (op) => {
      op.path = `friend_requests/${bru}_${ana}`;
      op.data = { ...op.data, from: bru, to: ana, fromName: 'Bruno', toName: 'Ana' };
    });
    await assertFails(run(t.db(bru), fromBruno));
    assert.equal(await has(recvPath), false);
    // ... and the blocker cannot ask the blocked person either
    await assertFails(run(t.db(ana), S.sendRequest.write));
  });

  it('a request sent by the person I blocked disappears with the block, so accepting it is denied (nothing created)', async () => {
    await bothActive();
    await t.seedRequest(bru, ana, { fromName: S.acceptRequest.input.fromName });
    await assertSucceeds(run(t.db(ana), blk.write));
    await assertFails(run(t.db(ana), S.acceptRequest.write));
    assert.equal(await has(pairPath), false);
    // even if the request is re-created behind our back, the block keeps accept denied
    await t.seedRequest(bru, ana, { fromName: S.acceptRequest.input.fromName });
    await assertFails(run(t.db(ana), S.acceptRequest.write));
    assert.equal(await has(pairPath), false);
  });

  it('crossed request is impossible across a block: blocked in either direction, the batch is denied', async () => {
    await bothActive();
    await t.seedRequest(bru, ana, { fromName: S.acceptRequest.input.fromName });
    await t.seedBlock(bru, ana); // bruno blocked ana (seeded: leaves his request, an inconsistency the rules still survive)
    await assertFails(run(t.db(ana), S.acceptRequest.write));
    assert.equal(await has(pairPath), false);
  });

  it('search: the card of somebody who blocked me is DENIED exactly like a hidden card; a missing handle is just "no document"', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await t.seedSocial(bru, { handle: 'bruno' });
    await t.seedSocial(caio, { handle: 'caio', discoverable: false });
    await t.seedBlock(bru, ana);
    const code = async (p) => {
      try {
        await getDoc(ref(t.db(ana), p));
        return 'ok';
      } catch (e) {
        return e.code;
      }
    };
    const blocked = await code(fx.lookups.handle.get); // handles/bruno
    const hidden = await code('handles/caio');
    assert.equal(blocked, 'permission-denied');
    assert.equal(hidden, blocked, 'blocked and hidden are indistinguishable');
    // The app maps both denied and "no document" to ONE message (SearchNotFound); a missing
    // handle is the only different answer at the rules level, and the screen does not show it.
    assert.equal(await code('handles/ninguem'), 'ok');
  });

  it('search by the blocker is also closed (the blocker does not find the blocked person), and unblocking reopens both', async () => {
    await bothActive();
    await assertSucceeds(run(t.db(ana), blk.write));
    await assertFails(getDoc(ref(t.db(ana), 'handles/bruno')));
    await assertFails(getDoc(ref(t.db(bru), 'handles/ana')));
    await assertSucceeds(run(t.db(ana), S.unblockUser.write));
    await assertSucceeds(getDoc(ref(t.db(ana), 'handles/bruno')));
    await assertSucceeds(getDoc(ref(t.db(bru), 'handles/ana')));
  });

  it('friends / received / sent lists of both people are empty after the block (nothing left for either)', async () => {
    await seedState({ pair: true, sent: true, recv: true });
    await assertSucceeds(run(t.db(ana), blk.write));
    for (const [uid, who] of [[ana, 'ana'], [bru, 'bruno']]) {
      const f = await getDocs(toQuery(t.db(uid), { ...fx.requestQueries.friends.query, where: [['members', 'array-contains', uid]] }));
      const r = await getDocs(toQuery(t.db(uid), { ...fx.requestQueries.received.query, where: [['to', '==', uid]] }));
      const s = await getDocs(toQuery(t.db(uid), { ...fx.requestQueries.sent.query, where: [['from', '==', uid]] }));
      assert.equal(f.size + r.size + s.size, 0, `${who} sees nothing`);
    }
  });

  it('deactivate / delete-account sweep removes REAL blocks created by the app payload', async () => {
    await seedState({ pair: true });
    await assertSucceeds(run(t.db(ana), blk.write));
    const db = t.db(ana);
    const swept = await assertSucceeds(getDocs(toQuery(db, fx.queries.blocks.query)));
    assert.deepEqual(swept.docs.map((x) => x.id), [bru]);
    await assertSucceeds(
      run(db, { mode: 'batch', ops: swept.docs.map((x) => ({ op: 'delete', path: `users/${ana}/blocks/${x.id}` })) }),
    );
    assert.equal(await has(blockPath), false);
  });
});
