// Replays the payloads the Dart app writes/queries (lib/data/social_payloads.dart) against the
// FINAL rules. Nothing is copied by hand: everything comes from fixtures/social_payloads.json,
// generated by test/social_payloads_golden_test.dart (UPDATE_GOLDEN=1). If the Dart code changes
// a field, the Dart golden fails until the fixture is regenerated; if the fixture then disagrees
// with firestore.rules, THIS file fails. Flow to update: docs/55.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { after, before, beforeEach, describe, it } from 'node:test';
import { assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import {
  collection, doc, getDoc, getDocs, limit, query, runTransaction, serverTimestamp, setDoc,
  where, writeBatch,
} from 'firebase/firestore';
import { PHOTO, U, agoDays, makeTools, newEnv } from './social_helpers.mjs';

const fx = JSON.parse(readFileSync(new URL('./fixtures/social_payloads.json', import.meta.url), 'utf8'));
const S = fx.scenarios;
const { ana, bruno } = U;

let env;
let t;
before(async () => {
  env = await newEnv();
  t = makeTools(env);
});
after(async () => env?.cleanup());
beforeEach(async () => env.clearFirestore());

const resolve = (v) => (v === fx.serverTimestamp ? serverTimestamp() : v);
const resolved = (data) => Object.fromEntries(Object.entries(data).map(([k, v]) => [k, resolve(v)]));
const ref = (db, path) => doc(db, ...path.split('/'));

// Executes one fixture "write" exactly as the Firestore data source does: a transaction (writes
// only; the Dart reads do not matter to the rules) or one batch.
const run = (db, write) => {
  if (write.mode === 'transaction') {
    return runTransaction(db, async (tx) => {
      for (const op of write.ops) {
        const r = ref(db, op.path);
        if (op.op === 'set') tx.set(r, resolved(op.data));
        else if (op.op === 'update') tx.update(r, resolved(op.data));
        else tx.delete(r);
      }
    });
  }
  const batch = writeBatch(db);
  for (const op of write.ops) {
    const r = ref(db, op.path);
    if (op.op === 'set') batch.set(r, resolved(op.data));
    else if (op.op === 'update') batch.update(r, resolved(op.data));
    else batch.delete(r);
  }
  return batch.commit();
};

const toQuery = (db, spec) => {
  let q = collection(db, ...spec.collection.split('/'));
  const clauses = spec.where.map(([f, op, v]) => where(f, op, v));
  return query(q, ...clauses, limit(spec.limit));
};

const clone = (o) => JSON.parse(JSON.stringify(o));

describe('Dart payloads (fixture) against the final rules', () => {
  for (const name of ['activate', 'activate_with_photo']) {
    it(`${name}: card + pointer in one transaction`, async () => {
      await assertSucceeds(run(t.db(ana), S[name].write));
    });
  }

  it('activate: taken handle is denied and creates nothing', async () => {
    await t.seedSocial(bruno, { handle: S.activate.input.handle, discoverable: false });
    await assertFails(run(t.db(ana), S.activate.write));
    await t.seed(async (d) => assert.equal((await getDoc(doc(d, 'social', ana))).exists(), false));
  });

  it('activate: non-Google provider denied', async () => {
    await assertFails(run(t.dbWith(ana, 'password'), S.activate.write));
  });

  it('activate: reserved handle, 21 emoji and 41 chars denied; 20 emoji ok (derived from fixture)', async () => {
    const withHandle = (w, h) => {
      const c = clone(w);
      c.ops[0].path = `handles/${h}`;
      c.ops[1].data.handle = h;
      return c;
    };
    const withNick = (n) => {
      const c = clone(S.activate.write);
      c.ops[0].data.nickname = n;
      return c;
    };
    await assertFails(run(t.db(ana), withHandle(S.activate.write, 'admin')));
    await assertFails(run(t.db(ana), withNick('\u{1F3AC}'.repeat(21))));
    await assertFails(run(t.db(ana), withNick('x'.repeat(41))));
    await assertSucceeds(run(t.db(ana), withNick('\u{1F3AC}'.repeat(20))));
  });

  for (const [name, photo] of [['changeHandle', undefined], ['changeHandle_with_photo', PHOTO]]) {
    it(`${name}: denied before 30 days, ok after; old handle freed`, async () => {
      const i = S[name].input;
      await t.seedSocial(ana, { handle: i.oldHandle, nickname: i.nickname, changedAt: agoDays(5), photo });
      await assertFails(run(t.db(ana), S[name].write));
      await t.seedSocial(ana, { handle: i.oldHandle, nickname: i.nickname, changedAt: agoDays(31), photo });
      await assertSucceeds(run(t.db(ana), S[name].write));
      assert.equal((await getDoc(doc(t.db(ana), 'handles', i.newHandle))).exists(), true);
      assert.equal((await getDoc(doc(t.db(ana), 'handles', i.oldHandle))).exists(), false);
    });
  }

  for (const name of Object.keys(S).filter((n) => n.startsWith('updateCard_'))) {
    it(`${name}: accepted`, async () => {
      await t.seedSocial(ana, { handle: S[name].input.handle, nickname: 'Ana' });
      await assertSucceeds(run(t.db(ana), S[name].write));
    });
  }

  it('updateCard: a photo outside googleusercontent (derived from the fixture) is denied', async () => {
    await t.seedSocial(ana, { handle: 'ana', nickname: 'Ana' });
    const bad = clone(S.updateCard_photo_on.write);
    bad.ops[0].data.photoURL = 'https://evil.example/x.png';
    await assertFails(run(t.db(ana), bad));
  });

  it('harness detects divergence: a renamed field in the fixture is denied by the rules', async () => {
    const bad = clone(S.activate.write);
    bad.ops[0].data.nick = bad.ops[0].data.nickname;
    delete bad.ops[0].data.nickname;
    await assertFails(run(t.db(ana), bad));
  });

  for (const name of ['close', 'close_with_invite']) {
    it(`${name}: one batch frees handle (and invite) and removes the pointer; others untouched`, async () => {
      const i = S[name].input;
      await t.seedSocial(ana, { handle: i.handle, inviteCode: i.inviteCode });
      await t.seedSocial(bruno, { handle: 'bruno' });
      await assertSucceeds(run(t.db(ana), S[name].write));
      await t.seed(async (d) => {
        assert.equal((await getDoc(doc(d, 'social', ana))).exists(), false);
        assert.equal((await getDoc(doc(d, 'handles', i.handle))).exists(), false);
        if (i.inviteCode) assert.equal((await getDoc(doc(d, 'invites', i.inviteCode))).exists(), false);
        assert.equal((await getDoc(doc(d, 'social', bruno))).exists(), true);
      });
    });
  }

  it('close: the pointer alone (handle kept) is denied', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await assertFails(run(t.db(ana), S.close_pointer_only.write));
  });

  const seedSweepDocs = () =>
    t.seed(async (d) => {
      await setDoc(doc(d, 'friendships', 'uid-ana_uid-b'), {
        members: [ana, 'uid-b'], createdAt: agoDays(3), aName: 'A', bName: 'B',
      });
      await setDoc(doc(d, 'friend_requests', 'uid-ana_uid-x'), {
        from: ana, to: 'uid-x', fromName: 'A', toName: 'X', createdAt: agoDays(1),
      });
      await setDoc(doc(d, 'friend_requests', 'uid-y_uid-ana'), {
        from: 'uid-y', to: ana, fromName: 'Y', toName: 'A', createdAt: agoDays(1),
      });
      await setDoc(doc(d, 'users', ana, 'blocks', 'uid-z'), { createdAt: agoDays(1) });
    });

  it('sweep queries return exactly this user\'s documents and sweepDelete removes them', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await seedSweepDocs();
    const db = t.db(ana);
    const found = {};
    for (const [kind, q] of Object.entries(fx.queries)) {
      const snap = await assertSucceeds(getDocs(toQuery(db, q.query)));
      found[kind] = snap.docs.map((x) => x.id);
    }
    assert.deepEqual(found.requestsSent, ['uid-ana_uid-x']);
    assert.deepEqual(found.requestsReceived, ['uid-y_uid-ana']);
    assert.deepEqual(found.friendships, ['uid-ana_uid-b']);
    assert.deepEqual(found.blocks, ['uid-z']);
    await assertSucceeds(run(db, S.sweepDelete.write));
    for (const q of Object.values(fx.queries)) {
      assert.equal((await getDocs(toQuery(db, q.query))).empty, true);
    }
  });

  it('door closed first (account deletion order): sweepDelete still works afterwards', async () => {
    await t.seedSocial(ana, { handle: 'ana' });
    await seedSweepDocs();
    const db = t.db(ana);
    await assertSucceeds(run(db, S.close.write));
    await assertSucceeds(run(db, S.sweepDelete.write));
  });

  it('account without social: sweep queries are allowed and empty', async () => {
    const db = t.db(ana);
    assert.equal((await getDoc(doc(db, 'social', ana))).exists(), false);
    for (const q of Object.values(fx.queries)) {
      assert.equal((await assertSucceeds(getDocs(toQuery(db, q.query)))).empty, true);
    }
  });
});
