// Replays the shared-profile payloads the Dart app writes (SharedProfilePayloads, docs/82 §9/§13)
// against the FINAL rules, like dart_payloads.test.mjs does for Phase 1.
//
// TODO(Fatia 1, docs/82 §15): the Dart side does not exist yet. The Dart golden test
// (test/shared_profile_payloads_golden_test.dart, UPDATE_GOLDEN=1) must generate
// fixtures/shared_profile_payloads.json; until then every test here is reported as "todo".
// Expected fixture format (same conventions as fixtures/social_payloads.json, plus nested values):
// {
//   "serverTimestamp": "$serverTimestamp", "deleteField": "$deleteField",
//   "clientTimePlusPrefix": "$now+",            // "$now+<ms>" / "$now-<ms>" = device clock +/- ms
//   "timestampPrefix": "$ts:",                   // "$ts:<ISO-8601>" = fixed Timestamp (nested ok)
//   "scenarios": { "<name>": {
//       "seed": { "<path>": { ...document as stored, same sentinels } },   // optional, rules off
//       "social": true,                          // optional: seed social/{uid} for the writer
//       "uid": "uid-ana",
//       "expect": "allow" | "deny",
//       "write": { "mode": "transaction" | "update" | "set" | "delete", "reads": [...],
//                  "ops": [ { "op": "set|update|delete", "path": "...", "data": {...} } ] } } }
// }
// Scenarios the Dart slice must cover (docs/82 §13): toggle on/off per section (set and update),
// last section off (delete), recalculation, 24 h pulse, setEpisodes with epsAt + orphan cleanup,
// SeriesBulkUndo restoring dates.
import { existsSync, readFileSync } from 'node:fs';
import { after, before, beforeEach, describe, it } from 'node:test';
import { assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import {
  Timestamp, deleteField, doc, runTransaction, serverTimestamp, setDoc, updateDoc, writeBatch,
} from 'firebase/firestore';
import { makeTools, newEnv } from './social_helpers.mjs';

const FIXTURE = process.env.SP_FIXTURE_PATH
  ?? new URL('./fixtures/shared_profile_payloads.json', import.meta.url).pathname;
const fx = existsSync(FIXTURE) ? JSON.parse(readFileSync(FIXTURE, 'utf8')) : null;

if (!fx) {
  describe('Dart shared-profile payloads (fixture) against the final rules', () => {
    it('fixtures/shared_profile_payloads.json generated by the Dart golden', {
      todo: 'Fatia 1: SharedProfilePayloads + golden do not exist yet (docs/84)',
    }, () => {});
  });
} else {
  let env;
  let t;
  before(async () => {
    env = await newEnv();
    t = makeTools(env);
  });
  after(async () => env?.cleanup());
  beforeEach(async () => env.clearFirestore());

  const resolve = (v) => {
    if (v === fx.serverTimestamp) return serverTimestamp();
    if (v === fx.deleteField) return deleteField();
    if (typeof v === 'string' && fx.timestampPrefix && v.startsWith(fx.timestampPrefix)) {
      return Timestamp.fromDate(new Date(v.slice(fx.timestampPrefix.length)));
    }
    if (typeof v === 'string' && v.startsWith('$now+')) return Timestamp.fromMillis(Date.now() + Number(v.slice(5)));
    if (typeof v === 'string' && v.startsWith('$now-')) return Timestamp.fromMillis(Date.now() - Number(v.slice(5)));
    if (Array.isArray(v)) return v.map(resolve);
    if (v && typeof v === 'object') return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, resolve(x)]));
    return v;
  };
  const ref = (db, path) => doc(db, ...path.split('/'));
  const run = (db, write) => {
    if (write.mode === 'transaction') {
      return runTransaction(db, async (tx) => {
        for (const p of write.reads ?? []) await tx.get(ref(db, p));
        for (const op of write.ops) {
          const r = ref(db, op.path);
          if (op.op === 'set') tx.set(r, resolve(op.data));
          else if (op.op === 'update') tx.update(r, resolve(op.data));
          else tx.delete(r);
        }
      });
    }
    if (write.ops.length === 1) {
      const [op] = write.ops;
      const r = ref(db, op.path);
      if (op.op === 'set') return setDoc(r, resolve(op.data));
      if (op.op === 'update') return updateDoc(r, resolve(op.data));
    }
    const b = writeBatch(db);
    for (const op of write.ops) {
      const r = ref(db, op.path);
      if (op.op === 'set') b.set(r, resolve(op.data));
      else if (op.op === 'update') b.update(r, resolve(op.data));
      else b.delete(r);
    }
    return b.commit();
  };

  describe('Dart shared-profile payloads (fixture) against the final rules', () => {
    for (const [name, sc] of Object.entries(fx.scenarios)) {
      it(`${name}: ${sc.expect ?? 'allow'}`, async () => {
        const uid = sc.uid ?? 'uid-ana';
        if (sc.social) await t.seedSocial(uid);
        for (const [path, data] of Object.entries(sc.seed ?? {})) await t.seedDoc(path.split('/'), resolve(data));
        const p = run(t.db(uid), sc.write);
        await ((sc.expect ?? 'allow') === 'allow' ? assertSucceeds(p) : assertFails(p));
      });
    }
  });
}
